// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEuSu4iS5qjFCwr-D-wx6OZJGBwBoe53s',
    appId: '1:339209347675:web:3b82fce30765d09e39957e',
    messagingSenderId: '339209347675',
    projectId: 'appfilms-81244',
    authDomain: 'appfilms-81244.firebaseapp.com',
    storageBucket: 'appfilms-81244.firebasestorage.app',
    measurementId: 'G-K0CN3CTKMQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCt0BlDjIx6wzzaqMhIsj7BwqBL0Ankbm8',
    appId: '1:339209347675:android:8fbee8914a8ff58c39957e',
    messagingSenderId: '339209347675',
    projectId: 'appfilms-81244',
    storageBucket: 'appfilms-81244.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkTV_8ZURttKWKwz8d-Z6DU4B1z1Eqfi0',
    appId: '1:339209347675:ios:e4ffe9bff402f42539957e',
    messagingSenderId: '339209347675',
    projectId: 'appfilms-81244',
    storageBucket: 'appfilms-81244.firebasestorage.app',
    androidClientId: '339209347675-833amjk9uq88rj3csgpt750qq7819v5d.apps.googleusercontent.com',
    iosClientId: '339209347675-69p6482c9pcsqrnuuqi1u3n0tn7rnjkr.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagramApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkTV_8ZURttKWKwz8d-Z6DU4B1z1Eqfi0',
    appId: '1:339209347675:ios:e4ffe9bff402f42539957e',
    messagingSenderId: '339209347675',
    projectId: 'appfilms-81244',
    storageBucket: 'appfilms-81244.firebasestorage.app',
    androidClientId: '339209347675-833amjk9uq88rj3csgpt750qq7819v5d.apps.googleusercontent.com',
    iosClientId: '339209347675-69p6482c9pcsqrnuuqi1u3n0tn7rnjkr.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagramApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDEuSu4iS5qjFCwr-D-wx6OZJGBwBoe53s',
    appId: '1:339209347675:web:9a2bc97e823e54b539957e',
    messagingSenderId: '339209347675',
    projectId: 'appfilms-81244',
    authDomain: 'appfilms-81244.firebaseapp.com',
    storageBucket: 'appfilms-81244.firebasestorage.app',
    measurementId: 'G-EWYBV79E26',
  );

}